// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmeDY7OeTD3tg63erLPOaM544XELCw0uc',
    appId: '1:606552538656:web:146e31faa017cb1d13c645',
    messagingSenderId: '606552538656',
    projectId: 'mood-journal-67',
    authDomain: 'mood-journal-67.firebaseapp.com',
    storageBucket: 'mood-journal-67.firebasestorage.app',
    measurementId: 'G-0F88HJHKSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvDgSnRzD26sIjrW-6Somrby49nWwsps',
    appId: '1:606552538656:android:9de018e0651bb7b013c645',
    messagingSenderId: '606552538656',
    projectId: 'mood-journal-67',
    storageBucket: 'mood-journal-67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHdexply2NcfKN_6C7aeXMttsQ_JK7eY',
    appId: '1:606552538656:ios:7aeaab2534cb49e413c645',
    messagingSenderId: '606552538656',
    projectId: 'mood-journal-67',
    storageBucket: 'mood-journal-67.firebasestorage.app',
    iosBundleId: 'com.example.moodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtHdexply2NcfKN_6C7aeXMttsQ_JK7eY',
    appId: '1:606552538656:ios:7aeaab2534cb49e413c645',
    messagingSenderId: '606552538656',
    projectId: 'mood-journal-67',
    storageBucket: 'mood-journal-67.firebasestorage.app',
    iosBundleId: 'com.example.moodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmeDY7OeTD3tg63erLPOaM544XELCw0uc',
    appId: '1:606552538656:web:0a3a66619990ad6d13c645',
    messagingSenderId: '606552538656',
    projectId: 'mood-journal-67',
    authDomain: 'mood-journal-67.firebaseapp.com',
    storageBucket: 'mood-journal-67.firebasestorage.app',
    measurementId: 'G-SYWCZK4121',
  );
}
